AUDIO_ENABLE = no
COMBO_ENABLE = yes

BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
RGB_MATRIX_ENABLE = yes
REPEAT_KEY_ENABLE = yes

WPM_ENABLE = no
EXTRAKEY_ENABLE = no
MOUSEKEY_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no

AUTO_SHIFT_ENABLE = no
ORYX_ENABLE = no
SPACE_CADET_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no

WEBUSB_ENABLE = no
ORYX_ENABLE = no

AUTO_SHIFT_ENABLE = no
AUTO_SHIFT_MODIFIERS = no

SEND_STRING_ENABLE = yes
TAP_DANCE_ENABLE = yes
